name: Update Data

on:
  workflow_dispatch:
  schedule:
    # Every 4 hour
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/data.yml"  # on data.yml (this file) change
      - "src/**"                      # on src change (change on author/images/series or any logic in scraping)
      - "assets/**"                   # on assets change (change on manually added assets)

permissions:
  contents: write

jobs:
  data:
    name: Check the repos
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: |
          git config --global user.name "Update Data"
          git config --global user.email "alfonsusac@gmail.com"
      - run: bun install
      - run: bun start